Done adding python support?

diff --git a/depfinder b/depfinder
--- a/depfinder
+++ b/depfinder
@@ -31,7 +31,6 @@ STARTDIR=""
 DEPVER=""
 DEBUG=${DEBUG:-0}
 DEPFINDERSEARCH="/usr/libexec/depfinder-search"
-PYTHONDIR=$( echo `python -c "import distutils.sysconfig; print distutils.sysconfig.get_python_lib()"|sed "s|/site-packages||"` )
 LIBDIRSUFFIX=""
 EXCLUDE="aaa_elflibs glibc glibc-solibs"
 
@@ -73,7 +72,7 @@ depfind()
 	touch DEPS$1
 	for i in `cat LIBS$1`; do
 		[ -h /$i ] && i=`readlink -e /$i`
-		$DEPFINDERSEARCH  $i $$ > TMP$1
+		$DEPFINDERSEARCH  $i $$ | uniq > TMP$1
 		if [ `cat TMP$1 | wc -l` -gt 1 ];then
 			cat TMP$1 | tr '\n' ' ' | \
 			sed "s/ /|/g" | sed "s/|$//" >> DEPS$1
@@ -218,26 +217,23 @@ fi
 
 # Handle python dependencies
 if [ $PYTHONDEPS -eq 1 ]; then
+
+	# Determine in which directories python looks for modules
+	python -c "import sys; print(sys.path)" | \
+	sed "s/'\|,\|\[\|\]//g" | \
+	sed "s/ /\n/g" > /tmp/depfinder.$$/PYTHONDIRS
+
+	# Find all python scripts in the package. Since python scripts
+	# are usually all over the place, we're looking everywhere
+	# anyway
 	touch /tmp/depfinder.$$/PYTHONFILES
-	# Find all python scripts in the package
-	if [ $CHECKALLFILES -eq 0 ]; then
-		# usually only in standard locations
-		find \
-		{sbin,usr/sbin,usr/bin,bin,usr/lib${LIBDIRSUFFIX},lib${LIBDIRSUFFIX},usr/libexec} \
-		-type f -exec bash -c \
-		"file {} | grep \"python script text executable\" 1>/dev/null && echo {} >> /tmp/depfinder.$$/PYTHONFILES"
-		\; \
-		2> /dev/null
-	else
-		# or anywhere in the package if -a is specified
-		find ./ \
-		-type f -exec bash -c \
-		"file {} | grep \"python script text executable\" 1>/dev/null && echo {} >> /tmp/depfinder.$$/PYTHONFILES" \; \
-		2> /dev/null
-	fi
+	find ./ \
+	-type f -exec bash -c \
+	"file {} | grep \"python script text executable\" 1>/dev/null && echo {} >> /tmp/depfinder.$$/PYTHONFILES" \; \
+	2> /dev/null
 
 	# Determine which python modules are imported (used)
-	touch /tmp/depfinder.$$/PYTHONMODULES
+	touch /tmp/depfinder.$$/PYTHONMODULESRAW
 	for i in `cat /tmp/depfinder.$$/PYTHONFILES`; do
 		grep "^ *import \|^ *from .* import " $i | \
 		grep -v " *#.*import" | \
@@ -247,10 +243,58 @@ if [ $PYTHONDEPS -eq 1 ]; then
 		sed "s/, /\n/" | \
 		sed "s/^ *//" | \
 		sed "s/\./@MODULESEPARATOR@/" | \
-		sed "s/\(.*\)@MODULESEPARATOR@.*/\1/" >> /tmp/depfinder.$$/PYTHONMODULES
+		sed "s/\(.*\)@MODULESEPARATOR@.*/\1/" | \
+		sed "s/^M$//" >> /tmp/depfinder.$$/PYTHONMODULESRAW
 	done
 
-	PYTHONMODULESLIST=`sort /tmp/depfinder.$$/PYTHONMODULES | uniq`
+	cat -A /tmp/depfinder.$$/PYTHONMODULESRAW | \
+	sort | sed 's/\^M\$\|\$//' | \
+	uniq > /tmp/depfinder.$$/PYTHONMODULESSORTED
+	
+	# Find which modules are included in the package and create a
+	# list with the ones that are not
+	touch /tmp/depfinder.$$/PYTHONMODULES
+	for i in `cat /tmp/depfinder.$$/PYTHONMODULESSORTED`; do
+		FOUND=`find ./ -type f | grep "/$i\.py$\|/$i/__init__\.py$\|$\.so"`
+		if [[ ! "$FOUND" ]]; then
+			echo "$i" >> /tmp/depfinder.$$/PYTHONMODULES
+		fi
+	done
+
+	# Remove python built-in modules from the list
+	python -c "import sys; print(sys.builtin_module_names)" | \
+	sed "s/'\|,\|(\|)//g" > /tmp/depfinder.$$/PYTHONBUILTIN
+	for i in `cat /tmp/depfinder.$$/PYTHONBUILTIN`; do
+		sed -i "/$i/d" /tmp/depfinder.$$/PYTHONMODULES
+	done
+
+	# Find the specific python files that provide the needed python modules
+	touch /tmp/depfinder.$$/PYTHONNEEDEDMODULES
+	for dir in `cat /tmp/depfinder.$$/PYTHONDIRS`; do
+		if [ -d $dir ]; then
+			for i in `cat /tmp/depfinder.$$/PYTHONMODULES`; do
+				if [ -f $dir/$i.py ]; then
+					echo "$dir/$i.py" \
+					>> /tmp/depfinder.$$/PYTHONNEEDEDMODULES
+					sed -i "/$i/d" /tmp/depfinder.$$/PYTHONMODULES
+				elif [ -f $dir/$i/__init__.py ]; then
+					echo "$dir/$i/__init__.py" \
+					>> /tmp/depfinder.$$/PYTHONNEEDEDMODULES
+					sed -i "/$i/d" /tmp/depfinder.$$/PYTHONMODULES
+				elif [ -f $dir/$i.so ]; then
+					echo "$dir/$i.so" \
+					>> /tmp/depfinder.$$/PYTHONNEEDEDMODULES
+					sed -i "/$i/d" /tmp/depfinder.$$/PYTHONMODULES
+				fi		
+			done
+		fi
+	done
+	# Display a warning for python modules that cannot be located in
+	# the system. These are not errors because the modules could be
+	# optional.
+	for i in `cat /tmp/depfinder.$$/PYTHONMODULES`; do
+		echo "`eval_gettext 'WARNING: python module $i not found.'`" >&2
+	done
 fi
 
 cd /tmp/depfinder.$$
@@ -280,6 +324,10 @@ if [[ `grep "=> not found" LIBS` ]]; then
 	sed "s/=> not found//" |\
 	sed "s/\t/ /" >&2
 	err
+fi
+
+if [ $PYTHONDEPS -eq 1 ]; then
+	cat PYTHONNEEDEDMODULES >> LIBS
 fi
 
 # Get the total number of libraries in the package 
