Added gettext support in depfinder. Created pot file and added TRANSLATORS file.

diff --git a/depfinder b/depfinder
--- a/depfinder
+++ b/depfinder
@@ -7,7 +7,17 @@
 #
 # Licensed under the GPL v3
 
-VERSION=1.0.2
+VERSION=1.1.0
+
+# Translations only work with utf8 locales
+if [ ! `echo $LANG | grep -i utf` ]; then
+	LANG=C
+fi
+
+# Gettext internationalization
+export TEXTDOMAIN="depfinder"
+export TEXTDOMAINDIR="/usr/share/locale"
+. gettext.sh
 
 CWD=`pwd`
 
@@ -24,8 +34,8 @@ LIBDIRSUFFIX=""
 # help message
 help_msg()
 {
-cat << ENDHELP
-depfinder: finds the dependencies of Slackware packages
+echo \
+"`eval_gettext 'depfinder: finds the dependencies of Slackware packages
 
 usage: depfinder [OPTIONS] <package.tgz|.txz|.tlz|.tbz or packaging-dir>
 
@@ -47,18 +57,15 @@ ENVIRONMENT VARIABLES:
   to add or exclude from the list depfinder reports (only package names,
   no version information):
     ADD
-    EXCLUDE
-	
-ENDHELP
+    EXCLUDE'`"
 }
 
 # version message
 ver_msg()
 {
-cat << ENDVER
-depfinder version $VERSION (c) 2009 George Vlahavas
-Run 'depfinder -h' for help information
-ENDVER
+echo \
+"`eval_gettext 'depfinder version $VERSION (c) 2009 George Vlahavas
+Run "depfinder -h" for help information'`"
 }
 
 # Routine to find out where each dependency comes from and output to
@@ -96,7 +103,7 @@ err()
 # If no arguments are passed, show an error message
 if [ $# -eq 0 ]; then
 	help_msg
-	echo "ERROR: No arguments found." >&2
+	echo "`eval_gettext 'ERROR: No arguments found.'`" >&2
 	err
 fi
 
@@ -131,7 +138,7 @@ do
 			# if it's out of range show help
 			else
 				help_msg
-				echo "ERROR: Number of jobs must be greater than one" >&2
+				echo "`eval_gettext 'ERROR: Number of jobs must be greater than one'`" >&2
 				err
 			fi
 		# if it's not a number show help
@@ -149,13 +156,14 @@ shift $((OPTIND-1))
 # Only one package at a time!
 if [ $# -gt 1 ]; then
 	help_msg
-	echo "ERROR: Too many arguments" >&2
+	echo "`eval_gettext 'ERROR: Too many arguments'`" >&2
 	err
 fi
 
 # test if the package file is there
 if [ ! -d $1 ] && [ ! -f $1 ] ; then
-	echo -e "ERROR: $1 not found\n" >&2
+	arg=$1
+	echo "`eval_gettext 'ERROR: $arg not found'`" >&2
 	err
 fi
 
@@ -165,7 +173,8 @@ if [ -d $1 ]; then
 else
 	# ... or has the .tgz|tbz|tlz extension (is a package file)
 	if [ ! `echo $1 | grep "\.t[gblx]z$"` ]; then
-		echo -e "ERROR: $1 is not a package file or a directory!\n" >&2
+		arg=$1
+		echo "`eval_gettext 'ERROR: $arg is not a package file or a directory!'`" >&2
 		err
 	fi
 fi
@@ -208,7 +217,7 @@ cd /tmp/depfinder.$$
 # Dump the dependencies to a file
 touch LIBSM
 for i in `cat FILES`; do
-	ldd ${STARTDIR}${i} 2> /dev/null \
+	LANG=C ldd ${STARTDIR}${i} 2> /dev/null \
 	| grep "=>" \
 	| sed "s/\(.*\) => \/\(.*\) \(.*\)/\2/" >> LIBSM
 done
@@ -225,7 +234,7 @@ sed "s/\(.*\)\/\(.*\)\.so\(.*\)/\2\.so/" >> INCLUDED
 
 # Check if any dependencies are not found and bail out if they are
 if [[ `grep "=> not found" LIBS` ]]; then
-	echo "ERROR: package requires libraries not found in the system" >&2
+	echo "`eval_gettext 'ERROR: package requires libraries not found in the system'`" >&2
 	grep "=> not found" LIBS >&2
 	err
 fi
